### ISSUE TITLE
Unexpected token in primary expression

### ISSUE THREAD

**Issue by BrunoCiccarino** [galaxy-lang/galaxy#17]
ERROR:
../../../examples/a.glx:1:11: Unexpected token in primary expression
 1 |   minus := -menos;
                 ^^^^^

**Comment by sm0gskr3am** [comment]
Issue fixed by following pull request: #20

**Comment by sm0gskr3am** [comment]
#20 Closed issue.

**Comment by sm0gskr3am** [comment]
@BrunoCiccarino Closed issue, by the following pull request: #20
